### ISSUE TITLE
Automate rule 3.9.5, points c, d, f.

### ISSUE THREAD

**Issue by sergeevNick** [eigen-space/codestyle#63]
This rule has partial automatisation in [#28|https://github.com/eigen-space/codestyle/issues/28] issue.
The `c` case has not implemented properly. For now it not uses type checking we only rely on the fact that enums and constants starts with upper case.
The `d` case has very complex logic when we can avoid else statement or unite if statement based on changes inside if/else block.
The `f` case has the same problems as described above. Complex logic not allows use simple approach with describing all available cases because there are a lot of them.

**Comment by derlagg** [comment]
Merged
