### ISSUE TITLE
Automate run the script that updates statistics about automated rules

### ISSUE THREAD

**Issue by Danilqa** [eigen-space/codestyle#94]
We talk about the script generates google spreadsheet: https://docs.google.com/spreadsheets/d/1phevI9VxclD8QsHYr5Stu-nlvUjJ3taBujgu1JOUqlg/edit#gid=408363158

Check list:

1. The script updates statistics about rules automatically

Open question:

1. How often should we recalculate statistics? It would be better if the script reacts on merge to `dev` (or maybe `master`).

**Comment by tohasan** [comment]
Closed due to https://github.com/eigen-space/dev-standards/issues/1
