### ISSUE TITLE
Split eslint configuration `plugin:eigenspace-script/all` into two separate: script and styles

### ISSUE THREAD

**Issue by tohasan** [eigen-space/codestyle#96]
Now we mix up rules that relates only to styles with rules that process scripts. Also we have prettier plugin that we should add as dependency to run rules that check styles. So at the moment we might get warning about peer dependency if we do not really need rules for styles and we do not add prettier dependency.

Check list:

1. We do not have warning about prettier if we do not use style rules
2. There are clear rule packages (set of rules) for scripts and styles

Note:

Do not forget about dependent projects.

**Comment by derlagg** [comment]
Merged
